name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Generate the Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Lazxrus
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark


      - name: Configure git for GitHub token
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Lazxrus/Lazxrus.git
      
      - name: Push output directory to output branch
        run: git push --force origin output
            
      - name: Push the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

